#!/usr/bin/env bash
# dpw@Darryls-iMac.localdomain
# 2022-02-05 14:51:04
#

set -eu

export container=debian-gcc

if docker ps | fgrep $container > /dev/null
then
  printf "copy local ssh keys to $container...\n"
  docker cp ~/.ssh/id_rsa $container:/root/.ssh/id_rsa
  docker cp ~/.ssh/id_rsa.pub $container:/root/.ssh/id_rsa.pub
  docker cp ~/.gitconfig $container:/root/.gitconfig
else
  printf "\nERROR! container $container is not running...\n"
fi

